### ISSUE TITLE
Create tables

### ISSUE THREAD

**Issue by stuntt101** [stuntt101/MiningProcessActivities#2]
Create database tables

**Comment by stuntt101** [comment]
Can I close this issue? You can request to close an issue once you have worked on it @ElphyRav . When you do your pull request, please specify what issue you would like it to address. @Lungelo , ifyou can, please show Elphy how to do this.

**Comment by ElphyRav** [comment]
Yes, you can close it as i have now manage to create and display tables for each process activity.
